### ISSUE TITLE
Uable to download JS bundle

### ISSUE THREAD

**Issue by johntom** [Qwikly/react-native-router-redux#18]
Hi,
I have a few working react-native examples working yet when I tried to run your demo I get Uable to download JS bundle. Did you torget to start the development server or connext your device? I tried to change the package manager to  "react-native": "^0.16.0", but got the same error.
Notes: win 10 with latest android install using genymotion
> npm install reports many errors i.e.
C:\Users\john\.node-gyp\4.2.3\include\node\v8.h(979): error C2989: 'v8::Data' :
class template has already been declared as a non-class template [C:\React\react
-native-router-redux\example\ReduxRouter\node_modules\bufferutil\build\bufferuti
l.vcxproj]
          C:\Users\john\.node-gyp\4.2.3\include\node\v8.h(74) : see declaration
  of 'v8::Data'
 C:\Users\john\.node-gyp\4.2.3\include\node\v8.h(93) : see declaration
  of 'v8::Primitive'
C:\Users\john\.node-gyp\4.2.3\include\node\v8.h(2052): error C2989: 'v8::Boolean
' : class template has already been declared as a non-class template [C:\React\r
eact-native-router-redux\example\ReduxRouter\node_modules\bufferutil\build\buffe
rutil.vcxproj]
...
1) React-native start (starts fine)
2) React-native run-android (runs fine)
3) Icon shows up but I get the error above
Thanks for this repo as it's exacty what I've been looking for. I will test on an apple device asap
John

**Comment by malkomalko** [comment]
@johntom are you referring to the Example project?  I believe the example is set up just for iOS at the moment.  You should be able to cd into the 'example/ReduxRouter' and run `npm install` and `react-native start`

**Comment by corymsmith** [comment]
@johntom What version of Node are you running? That particular error doesn't look related to this module.

**Comment by johntom** [comment]
Yes, I saw the index.android.js file and was hoping.

Thanks,

J

**Comment by johntom** [comment]
Trying to run on a win 10 using android.
node v4.2.3
npm 3.5.2

**Comment by JeJan** [comment]
having the same error on android and ios cannot build anymore.
I found out it is not compatible to the current react-native version anymore, a downgrade to the versions of the examples worked great.

was using:
"react-native": "0.18.0-rc",
"react-redux": "4.0.6",
"redux": "3.0.5",
"redux-thunk": "1.0.3"

**Comment by malkomalko** [comment]
The example should now be working with 0.16, but I haven't tried with 0.18 yet.
